This program might be compiled with Borland C++ 5.02 or Borland C++ 5.5.  If it
is the DOS build, it was compiled with Borland C++ 5.02, and the following 
applies:
 
 According to the Borland language products "General Terms That Apply to Compiled
Programs and Redistributables:"
 
    The license granted in this statement for you to create your own compiled 
    programs and distribute your programs and the Redistributables is subject 
    to all of the following conditions:
    
    All copies of the programs you create must bear a valid copyright notice, 
    either your own or the Borland copyright notice that appears on the
    original diskette label on this package.
    
    .
    .
    .
    
    All other requirements of the copyright law, international treaty, and 
    Borland's No-Nonsense License Statement and Limited Warranty continue to 
    apply except as provided otherwise above.  
 
 If it is the Win32 build, it was compiled with Borland C++ 5.5, and the 
following applies:
 
 According to the "Inprise No-Nonsense License Statement and Limited Warranty:"
 
    All copies of the programs you create must bear a valid copyright notice,
    either your own or the Inprise copyright notice that appears on the
    original diskette label on the Software.
 
 I put this into the realm of "nonsense," myself, but just to keep Borland
happy:
 
    Copyright 1987, 1991 Borland International, Inc.  All rights reserved.
    (For 5.02)
 
 or
 
    Copyright (c) 2000 Inprise Corporation.  All rights reserved.
    (For 5.5)
 
 I'm just happy that Borland didn't stipulate putting the copyright in an
obvious location.  
