Application
Border
Configuration
Door 
Local 
Exclusive 
Name
Old 
Password
Textfile
With protocol upload 
File-linked 
%0-only 
%A
%1
Exclude %6
  -- Must be logged in.
  -- You cannot enter borders.
 3.ED%c0> %s
 3.ED?0> this menu
  -- You cannot enter exclusive %s.
  -- %s is read-only.
  -- Only %d %s per %s.
Clear aborted %s
 No aborted %s.
 Using aborted %s.
full path to file
 @ 
{}
  -- Color and case changes only.
  -- You cannot create more than %s %s per call.
  -- You cannot create %s here.
Surname / Title
  -- %s cannot enter title and surname.
  -- You cannot enter file-linked %s.
Enter 
  -- Must log in to enter.
 Border lines not enabled!
2Border %d:0 
Empty!
border line to change
border line
Make %s public
Install "%s" as a %s %s
public
hidden
{}
{}
 You cannot exclude this %s.
Exclude %s from 3G2>oto loop
%s now excluded from your 3G0>oto loop.
%s now in your 3G0>oto loop.