.dat
Compiling dictionary.
Input file is bad. (%s)
Write failed.
Compiling dictionary. (Letter %c; %s words)
Done. %s words in dictionary.
Could not open output file.
Could not open input file.
name of source file
ENG-AM.TXT
Configure
path to Citadel-86 v3.45 CTDLCNFG.SYS file
CTDLCNFG.SYS
Could not open file: %
Reading %s...
Can only import Citadel-86 files into a fresh system.
#CRYPTSEED
#MESSAGEK
#MAXROOMS
#LOGSIZE
#HELPAREA
#LOGAREA
#ROOMAREA
#MSGAREA
#FLOORAREA
#HOLDAREA
#INFOAREA
#BIOAREA
Creating configuration files...
ImportCit86Data()
#NODETITLE
\
#ENTEROK
#READOK
#ROOMOK
#COM
#SYSBAUD
#MODEMSETUP
#SYSOPNAME
#DISK-FREE
#%s "%ld"%s
Could not read %s from %s.
#MSG-SLOTS
#MAIL-SLOTS
ctdlflr.sys
Importing Citadel-86 floors to Citadel+ halls...
ImportCit86Data()
ctdlroom.sys
Importing Citadel-86 rooms...
msgtmp.c86
%lu %hd%s
.
ctdllog.sys
{}
Importing Citadel-86 users...
%hd.bio
ctdlmsg.sys
Finding first Citadel-86 message...
Could not find first Citadel-86 message!
Importing Citadel-86 messages...
