#BANPORT
!%s
-- Command disabled.
%
idle
Zero
Negative 
Cannot create %s!
#NOSPASM
roman
%s: [%08x] {%ld} (%s) %s%s
%s: [%08x] %s%s
%s: [%08x] {%ld} %s%s
20
Cannot find %s!
%02d%s%02d
Signature
Regular shell failed; attempting super shell.
Initializing serial port...
%02ld
Unknown %s keyword: %s
NetLogout %s (Succeeded)
Display system bulletin
[Fixed corrupted message]
decompress(): Unknown ESC value: %d.
 Please wait...
 Temporarily unable to display buffer.
RE
Connection to 4%s3 has been lost.
Pausing for ^BP...
Finding visible messages...
Could not re-open printer file after shell!
Lots
Preparing to exit...
REQ
%30.30s³%s³%s³%s³%s³%c%c%c%c%c%c%c³%s³%s³%s³%s
   
Sysop menu
Prt
Chat
RCht
    
rcht
 "3?0" for menu, "3H0" for help.
DE
SpTm
%02d
%s - EOF detected!
¹³)}¯>
]:)}>>
0x
2%s? (
 %10ld
N/A
 %10s
 %s0
Confirm
  -- You are not allowed to read the %slog
Could not load messages.
Save
 NA 
Change your initials and password
ATPNUSM
       
NC
%s>'s directory (%s) not found.
 %-*s0
 3%-*s0 #%s %s
Dude!
 #%s %s
19
CD
timeout
didn't receive message file
 3%s0
didn't receive room request file
temp log
Cannot open %s!
too many invalid characters
Cannot rename %s!
^BH
Hanging up...
Cannot read %s!
Pausing for #CONNECTWAIT...
Auto ANSI test . . .
Switching to %ld baud...
 ANSI detected . . .
 ANSI not detected . . .
Wait 5 seconds, or hit (space), (ESC), (A)NSI, or (S)top . . .
Ring.
Carrier lost.
Pausing for bad password...
 [%s0]
Normal
Blinking
Inverted
temp log2
Boldface
Underline
Not logged in
%s @ %s
%s too long; must be fewer than %d characters
Sorry, no additional help is available.
%s '%02d
A "%s" %s already exists.
name for new %s
description for new %s
your mom
Do you really think that anything could help her?
Room "%s%c" created by %s
%4lu
Netcmd
%s0: Old group was %s.
%s0 logged out.
 Your balance is %s %s
 %s %s used this call
 You entered %s %s and read %s.
 You were logged in for: %s
 You were caller #%s.
Mark
Error parsing time, please try again or press 3?0 for help.
%4ld
Memory Dump
string to search for
new address to inspect
%p
Search string not found.
Please wait, searching...
%p  %02x %02x %02x %02x %02x %02x %02x %02x  %02x %02x %02x %02x %02x %02x %02x %02x  %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c
%y%b%D %X
a
the
an
#UNSUBSCRIBE
Cannot allocate screen
 Keys: , , PgUp, PgDn, Home, End, Esc, S, B, G, W ³ %s line%s back
#SIGNATURE
/
Special time is now beginning, you have no time limit.
Special time is over. You have %s %s left today.
 Only %s %s left today!
%s does not exist
Error reading message.
  %s %s.
Your transfer took %s %s. You have been %s %s %s.
minute
minutes
)[
charged
credited
  -- %s has no application.
%30s
Message::ReadHeader: bad HowToRead
  -- Cannot find application directory.
%s change to: %s
Error parsing date, please try again or press 3?0 for help.
 No such %s "%s".
%13s
Connect 57600
Bad value %d "%s"
Enter line to go to:
Swapping, please wait.
[%s: %s]
Use the EXIT command to return to %s
To mailing list: 
A %s3 has been left in this room by 4%s3.
Connect
Connect 1200
Connect 2400
Connect 9600
No carrier
Error
No dialtone
Busy
No answer
Connect 12000
Connect 14400
Connect 19200
Connect 38400
Connect 57600
Connect 4800
Connect 7200
Connect 16800
Chat off
Chat on
Shutdown Citadel; errorlevel %s
Cannot network with a %s logged in.
%s - not enough memory
]:0 
%c%c%c%c
00:00
%25.25s
%4s
%c%c%c%c%c
%2.2d
%12.12s
Edit
Reading 
%15.15s
"3?0" for menu.
%5.5u
Shell: "%s"
Local Net 6.9 incorporation
To incorporate use .S6 menu.
Local Net 6.9 fetch.
No NODES.CIT entry for "%s".
Fetching for "%s"
To fetch use .S6 menu.
Run script: "%s"
 Unknown event type %d
 @ %s
%c%s
0
2
  -- Not a directory %s.
Upload 
#%s%s
#%s %u%s
4%s3 has left this %s3.
4%s3 has entered this %s3.
#%s %lu %lu %hd %hd %d%s
#%s "%s" "%s"%s
#%s "%s"%s
%s\LE%hd.%s
%lu%s
             
mzs
AD
, %s
new time
Quack!
%c%-30s %c%c%c 
%02d%s%02d %02d:%02d:%02d
After time and date changed
Before time and date changed
, 
%H:%M %m/%D/%y
%c%c
  -- Must be logged in.
Enter text to search for:
:
%H:%M:%S
%m/%D/%y
%c0 (LOCAL)%s
%c%ld%s
%c%d%s
%c%u%s
Name
%c%s%s
".
%s, %s
  -- Your title and surname have been locked.
title
surname
No log entry for "%s".
sea
Executing cron event: %s.
Cron timeout in: %ld:%02ld.
Rcvd: 
Goto 
Bypass to 
%s to go to
Help 
Intro to %s
Sent: 
new date
 Keys in buffer: %s
%y%b%D  %H:%M:%S
[%s0] 
Enter name of file to write to:
Enter number of lines (starting at top of screen):
3%s0
 [%s0]
 3%c0> %s
Censor
Uncensor
Pull
, boolean %s-only
------
Wow!
Wow^%s!
Wow your mom!
Mom!
Double 
Mom^%s!
%s%s %-10s %-32s %s
Wowcount
wowcount
filename
12.0
14.4
16.8
19.2
28.8
38.4
57.6
115K
230K
[ ]
/-\|
mavencit
Lobby
Wow%c
COLOR
wow
"%s"
-end-
.%s
Locl
 "%s"
   
!
?%s%s
%s %s %ld %d %s
Xpert %s
Off
On
Auto verbose: %s
MONO
EXPERT
Next %s: 
Previous %s: 
COM%d%s%s
pscalut
pscalutf
>
<
%02d:%02d:%02d
%02d%s%02d
       
MXhi36X%sXhi0X
List %s 
 -- 3%s0
Tnet
Unkn
%ld %ld %ld
Created by: %s
:|<>
UNKNOWN
> 
#DIRECTORY
    
%-31s
Cannot jump back.
Unknown log extension: %s
  -- File "%s" already exists.
(%s)
HELLO
CHAT
LOGOUT
Menu
Message::Store: bad HowToSave
#REFUSER
NOCHAT
BLB
NOVICE
0<3Reversed %c0>
Add
Remove
****
 3%c0> %s
  -- %s has an invalid directory!
!pooP
!tihS
Poop!
Shit!
Volkswagen!
No %s "%s".
 (Succeeded)
 (Failed)
 (In progress)
%H:%M
 %s %s:
 3%s:0 
8  { Databits }
LOCAL
Kill "%s>"
REMOTE
Cannot kill %s>, %s>, %s), or %s>
Room "%s>" killed by %s
%d, 
  -- "%s" is not a legal filename.
comments
%s moved to just after %s.
Aide
Sysop
Building addresses... %%00
search text
, done.
Net mail
Value out of range.
Range is %s - %s
Cannot find %s. Looking for %s at byte %s!
%s day%s %02d:%02d:%02d
Normal Connection
, owned by %s %s
Windowed in %s:
%4lu total,
%4lu %s, %4lu new
, (Mail)
Run application: %s
End application
2+0
Continue
2-0
Volkswagen 
2>0
21*0
2<0
  %-8s
.hlp
 2 * 1WARNING!!!02 * 0 Empty %s not saved!
*.HLP
%s%d.%s
subject
%s.%s
Address
wow.log
The cows are home.
%02d:%02d:%02d
%s.%2.2s@
File not found
.HLP
name
  -- No file "%s".
 0<3J0>ump <3P0>ause <3S0>top
No %s description "%s".
.BLB
 %s%s
You have up to %s characters.
Enter %s (end with empty line).
 Buffer overflow.
.
%X
%x
(
)
AND
OR
NOT
XOR
???
New node found on network in message %s: %s0, %s (%s) %s
%s\mail.%s
  -- Not a windowed %s.
,
Failed to allocate space for directory info
 3%s %s03 is contained in:0
Application
%s "%s>" killed by %s
Following %s #%s deleted from %s> by %s:
Security violation on directory %s by %s. %s unverified.
%s "%s>" added to %s "%s" by %s
%s "%s>" excluded from %s "%s" by %s
%s added to %s %s by %s
%s kicked out of %s %s by %s
%s "%s%c" created by %s
Moving to previous room: 
**Deleted**
parseArgs()
CreateRoomSummary()
%s stub
#MAILLIST
3This room has an invalid Net ID.0
TELNET
ÍÍÍÍ %y%b%D  %H:%M:%S ÍÍÍÍ 
 %y%b%D  %H:%M:%S 
3%s0%*s
, boolean-group owned
Reply
Multi-group
%s%s
 Local editor only!
 3.%c?0> this menu
We already have a %s.
 3%s accessible:0
  -- Command disabled while using personal %s.
 Reading %s %s only.
8N1
GR
NG
Exclude %s "%s>" from %s "%s"
Room "%s>" excluded from hall "%s" by %s
 Excluded %s>%s
Add %s "%s>" to %s "%s"
Room "%s>" added to hall "%s" by %s
 Added    %s>%s
12/31/99
2Enter %s:0 
%s table full.
%ld BAUD,N,8,1%s
Local
2Enter %s%s [%s%s%s]:0 
 Sorry, must be no more than %s
Leave a %s2 to the sysop
 pw:
Move %s
This %s cannot be moved.
 Sorry, must be at least %s
 in:
 No menu "%s"
COMSPEC
Room missing in table!
, Net ID %s
, owned by %s %s
 * System available * 
 nm: %s0
 (Node)
 %s No '%s' user found on %s.
%u%s
Header scan -
Local Citadel-86 fetch.
Local Citadel-86 incorporation.
Send to %s, %s (%s)
Invalid address in #ADDRESS keyword
Too few arguments for #ADDRESS keyword
Header scan +
 %-37.37s³ %-32.32s³ %s
Verbose -
, privileges %s %s
Yes
No
, hidden
Verbose +
Ready to execute event.
Continuous -
Continuous +
Stop
[Not logged in]
, anonymous
[xmodem]
[crcxmodem]
[1kxmodem]
[zmodem]
Bad command line: %s
%s /c %s
Next
Censor
, BIO
, moderated
, read-only
, download-only
Mark
An exclusive %s03 has been sent to you by %s03 in %s03.
, networked/shared
Kill
Jump
%s for %s
On
Off
new name for %s
only.
Press CR for: 
*UNLISTED
%ld%s
%d%s
Cannot open archive file!
Anonymous message #%s
Error mailing to %s, %s0 in old buffer.
Release %s
 %s forwarded to 
 %s forwarded to Sysop on %s
 Sysop %s forwarded to "%s"
recipient
 Exclusive %s to "%s"
It is now %s.
Citadel was up for %s.
, application
, autoapp
, permanent %s
5%s6Directory path is %s
5%s6Application is %s
5%s6%s description file is %s
5%s6%s info-line is: %s
%s base destroyed since last call!
All %s pointers reset.
 0<3J0>ump <3N0>ext <3P0>ause <3S0>top
 3%s:0
Add %s to %s %s
Remove %s from %s %s
  -- %s is locked.
%s added to group %s by %s
%s kicked out of group %s by %s
 No such %s.
month
Console
Remote 
%s for new %s
, Next %s: 
Jump back to
3You have mail here.0
Following message #%s deleted from %s> by %s:
*TWIT
*PERMANENT
 No "%s" known.
  %b%D %H:%M
%s file missing! (%d)
Event Success date is: %s
3You have unread old mail here.0
Freeing system tables twice.
Incorrect initials and password.
your old password
your new initials
your new password
Poor password
NetLogout %s (Failed)
Event Success time is: %s
your old initials
%s "%s0"
 2 * 1WARNING!!!02 * 0 Dangerously low on memory!
 No such %s, or not accessible from here.
 2 * 1WARNING!!!02 * 0 Exceedingly low on memory!
Sysop menu
%s0 logged out @ %s
YNA
2Change:0 
YN
Abort
No
Yes
Goto next %s with mail: 
Specified route for %s (%s) is invalid.
#ROUTE
#ADDRESS
To ensure proper routing, please verify your spelling of "
TRUE
FALSE
3811
%03d
Bad bad memory stuff.
None
%s:
<3S0> to save, <3A0> to abort
3%s0
%s total, 
%s %s
, 4%s new0
rgnehitd
Run %s
 3.%c%c0> %s
 '"/\[]:|<>+=;,
%02ld:%02ld:%02ld
upload()
3,0 
3.0
Bad bad.
(NULL)
 Timeout... 
CMP_ERROR
CMPI_ERROR
DEANSI_ERR
Save changes
Abort
Abort changes
STRIP_PUNCT_ERR
Could not revert to original.
citrun
*SYSOP
*AIDE
*NODE
Cannot write %s!
Cannot unlink %s!
Cannot allocate file buffer for %s.
Cannot allocate space for file buffer
4%s3 has logged out.
FATAL SYSTEM CRASH: 
Security violation on directory %s by %s. User unverified.
Connect 230400
Connect 28800
f6disabled
initCitadel()
Aa#?*Xx
*NETWORK
*NOMAIL
 3No such bulletin!0
2Enter choice, "3?2" for menu, or <3CR2> to continue:0 
 "3H0" for help
 "3?0" for menu
 "3L0" to login
Security violation, your account is being held for sysop's review
Super secret error #x14h-22a!!
%s%s%s%s
Welcome to %s, %s, %s
To ensure proper routing, please verify the address "%s".
Hanging up (%s)...
Could not load changes.
T
F
Y
N
.exe
