2Processing network commands.0
Unknown network command "%s"
*%s
2Error responding to network command.0
 Software: %s%s
 OSver: %d.%02d
 #SYSOP: %s
 #MDATA: %d
 #DUMBMODEM: %d
 #INITBAUD: %ld
 #MINBAUD: %ld
 #MODSETUP: %s
 #MODUNSETUP: %s
 #DOWNSHIFT: %s
 #DIALSETUP: %s
 #DIALPREF: %s
 #DIALRING: %s
 #DIALRINGWAIT: %d
 #UPDAYS:
 #UPHOURS:
 #HANGUPDELAY: %d
 #HANGUP: %s
 #OFFHOOKSTR: %s
 #BAUDPAUSE: %d
 #FILEBUFSIZE: %u
 #AUTOANSI: %d
 #MESSAGEK: %ld
 #MAXFILES: %d
 #MAXLOGTAB: %hd
 #MAXROOMS: %hd
 #MAXHALLS: %hd
 #MAXGROUPS: %hd
 #MAXBORDERS: %d
 #NMESSAGES: %lu
 #OVREMS: %d
 #OVREXT: %d
 #BIOS: %d
 %d
 %s.%s %s%s
 #VMEMFILE: %s
 #CHECKCTS: %d
 #SCROLLSIZE: %u
 #SCROLLCOLORS: %d
 #MAXJUMPBACK: %d
 #STATNUM: %d
Unknown node "%s"
Error reading NODES.CIT entry for "%s"
Report for "%s"
 Node: %s
 Region: %s
 Address: %s.%s
 Baud: %ld
 Timeout: %d
 Protocol: %c
 Waitout: %d
 Mailtmp: %s
 Autohall: %s
 Autogroup: %s
 Mapunkgroup: %s
 Network: %d
 Zip: %s
 Unzip: %s
 Autoroom: %d
 Verbose: %d
 Request: %d
 Gateway: %d
 Fetch: %d
 Netfail: %d
 Redial: %d
Poop count of %s: %ld
Poopuser: "%s"  Poopcount: %ld
Finger of user %s:
Could not load user %s off disk.
Not Active
NCR
DoDebugCommand()
