Connection %ld: %s%s connection %s %s
elnet
odem
T
t
M
m
from
on
Carrier-Loss on %s
%s%s connection terminated
Carrier-Detect (%lu) on %s
Unknown
 type of
Password changed
User %s terminated
Empty room %s> deleted by %s
Dropping connection on banned port %s
Carrier dropped on %s
  ----- %4d messages expired
  ----- %4d messages duplicate
NetLogout %s (Failed)
NetLogout %s (Succeeded)
Logout %s
  ----- %4d messages entered
  ----- %4d messages read
Cost was %ld
Illegal inits;pw: %s;%s (%s %s)
Illegal inits;pw: %s;%s
File%s %s unlinked in %s] by %s
Text download of file %s in room %s]
Console session
Login %s from %s
NetLogin %s from %s
Hung up, these were inits;pw: %s;%s (from %s)
Citadel terminated
Citadel started
File %s renamed to file %s in %s] by %s
Text upload of file %s in room %s]
Zmodem (internal) download of file(s) %s in room %s]
WC download of file %s in room %s]
Zmodem (internal) upload in room %s]
WC upload of file %s in room %s]
Sysop full-path %s download of file %s in room %s
Queued %s download in %s
%s file upload in room %s]
%s download of file %s
%s upload of file %s in room %s]
Network with "%s"
