doEnter()
loginNew()
newUserFile()
fullScreenConfig()
LockMenu()
substr()
dial_out()
securityViolation()
RomanInput()
RomanOutput()
showconfig()
Zmodem_Send_Batch()
Zmodem_Receive_Batch()
attributes()
entertextfile()
renamefile()
unlinkfile()
doTheDownload()
ActuallyDoTheUpload()
MoveFile()
editRoom()
killempties()
killroom()
doConsoleSysop()
LoadAndPrintMessageByID()
showMessages()
LoadFileInfoForDirectory()
initCitadel()
doAide()
editText()
getText()
replaceString()
ListRoomsNotInPersonalHall()
doFileQueue()
doDownload()
doUpload()
doChat()
doVolkswagen()
doY()
doFingerEdit()
terminate()
makeMessage()
spellCheck()
getnode()
doRead()
autoroom()
xhallfunc()
windowfunc()
fkey()
makeRoom()
CreateConfigurationFile()
groupfunc()
SendMailToList()
xsend()
xreceive()
ReadGrpdataCit()
SaveStub()
checkAutoArchive()
ReadExternalCit()
ReadProtocolCit()
ParseMdmresltLine()
ReadMdmresltCit()
ReadMCICit()
addtomsglist()
sortmsglist()
copymessage()
deleteMessage()
insert()
copymsg()
net69_incorporate()
readAplFile()
LogExtensions::Load()
ListAllRooms()
SetFileInfo()
IsNetIDInNetIDCit()
AddNetIDToNetIDCit()
LoadAndTestIfShouldSaveMessage()
theAlgorithm()
theOtherAlgorithm()
runScript()
getFmtString()
dispBlb()
dispHlp()
showMenu()
net69_menu()
buildaddress()
save_mail()
makeBorders()
net86_incorporate()
CreatePathDat()
listTaggedAuthors()
messageEditOptions()
DoUserlogEdit()
DoEnterConfiguration()
readNetCmdTmp()
decrypt()
encrypt()
ReadMsgFl()
readconfig()
checkdir()
AddLock()
do_SysopEnter()
LockMessage()
GetSysPWHandler()
PrintMessage()
printheader()
ShowWhyMayNotSeeMsg()
putheader()
showinfo()
FillFileInfo()
listRooms()
net_slave()
TermCapC::Load()
doFingerUser()
editIt()
ReadCommandsCit()
ReadTextfile()
EnterTextFile()
EnterWithProtocol()
ReadWithProtocol()
ReadArchive()
