Options:
Helpful hints
Last old %s on 3N0>ew
Auto next %s
%s descriptions
%s descriptions
%s info-lines
Titles/Surnames
Subjects
Signatures
Auto-verbose
Twirly cursor
Pause after %s
Clear screen before %s
Minibin login stats
Verbose continue
View censored %s
Borders
Verbose logout
You are here
IBM %s prompts
Wide %s0 list
Show commas in numbers
3P0 Unpauses
Auto-idle
Bunny filter
Roman numerals
See your own chats
Erase prompt before events
.
.
.
.
...Reserved
4Enabled:0 
4Disabled:0 
[%s0] 
%s0
   %s0
Access:
(Node) 
Aide 
Sysop 
Dungeoned 
Network 
Unlisted 
Permanent
4%s:0 
Exclusive %s forwarded to 
4Address:0          %s
4Default %s:0     
4Default protocol:0 %s
4Net prefix:0       %s0
4Prompt format:0    %s0
4Time/date stamp:0  %s0
4Verbose   "    :0  %s0
4Signature:0 %s0
Terminal:
4Terminal type:0 %s.
4Attributes:0 0Normal3,0 1Blinking03,0 2Inverted03,0 3Boldface,0 4Underline03.0
Width %s3,0 
uppercase only3,0 
%sinefeeds3,0 
%s lines3,0 
%s nulls3,0 
%sabs3.0
4More Prompt:0 %s
4Time in account:0 %s %s.
4Poopcount:0 %s
Error reading NODES.CIT entry.
{}
{}
L
No l
T
No t
.
.
Music3,0 
4Using personal %s04.
SuperSysop 
Banned 
