[On %s %s (%s0)]
Release
YNK
Kill
Respond
To mailing list: 
Reply to <3U0>ser, <3M0>ailing list or <3A0>bort: 
Mailing list
%s number to read
Journalling %s: 
date for reading
Read %s before or after %s
BA
Before
After
   [3%s%s has been excluded0]
Exclusive 
2This message is encrypted.0
decryption key
X
   [3%s skipped because it has advanced MCI0]
 3{0%s3}0
    # %s of %s
 (Reference id # %s)
    Source id # is:  %s
    Source room is:  %s03
    Linked file is:  %s
     Linked app is:  %s
     Path followed:  %s
   Source software:  %s
       Forced path:  %s
 From 
 {%s}
 To %s03
 Forwarded to %s03
 [reply to %s]
 [reply]
 [received]
 [reply sent]
 In %s03>
 (%s only)
 1[problem %s]03
 [moderated]
 [viewable %s%s]
problem 
moderated
 [file-linked]
 1[censored]03
    0%%4%s0
2Generating receipt confirmation...0
Receipt confirmation
 Message #%s from %s @ %s received by %s @ %s.
 Received via: 
 Message #%s from %s received by %s.
2Error generating receipt confirmation0
(%s) Copy of scrolled %s.
(%s) Censored %s.
(%s) Not logged in.
(%s) Copy of own problem-%s %s.
(%s) Released original %s.
(%s) Problem %s %s.
(%s) Moderated %s.
(%s) Not in %s.
(%s) %s does not exist.
(%s) Not your mail.
    %s
[%s03] 
4%s03
 [%s03]
 (Local %s)
 (Receipt confirmation requested)
         To: 4%s0
    Subject: 4%s0
(%s) %s has scrolled.
