[
Timeout or full]
PreDial (%s)
Dialing (%s%s) ... 1 
Dialing (%s%s) ... %s 
Download (%s) (%s) (%s)
Pause for (%s)
Repeat (%s) (%s) (%s)
Wait for (%s)
Send (%s)
Upload (%s) (%s) (%s)
(Attempting to open %s with mode "%s"... 
Succeeded.)
Failed.)
Sending mail to %s @ %s0
To path: %s
From path: %s
Using forced path
...NOT!
Sending through %s
Could not open file: %s
Spasming
 even though we had a #ROUTE
To our locID.
Checking locID.
To locID %s.
Checking %s
Expired
Wrong locID.
Saving to %s.
Been there check failed.
 (%s)
indexslot() error
LoadAndPrintMessageByID(): Bad ID (%s)
LoadAndPrintMessageByID(): Bad location (%s, ID %s)
    Unknown field: (3%c0) %s
Room #%s
Compressed - %s to %s
{}
Sound effect %s
Play sound %s
New tempo: %d
Octave out of range (%c).
Invalid note: %d
Skipping "%c" at %d
Note %d - D %3d; Len %ld
(Attempting to change to %s... 
No ROOMREQ.%s
ROOMREQ.%s
Journal file already open!
No archive file!
No job
(Checking for existence of file %s... 
It exists.)
It does not exist.)
(Attempting to delete file %s... 
(Attempting to rename %s to %s... 
(Buffered open of existing file %s.)
(Attempting buffered open of file %s... 
(Attempting buffered creation of file %s... 
Z_SendHexHeader
Z_GetHeader
Z_GetBinaryHeader
Z_32GetBinaryHeader
Z_GetHex
Z_GetHexHeader
Z_TimedRead
send_Zmodem
ZS_SendBinaryHeader
ZS_32SendBinaryHeader
ZS_SendData
ZS_32SendData
ZS_GetReceiverInfo
ZS_SendFile
ZS_SendFileData
ZS_SyncWithReceiver
ZS_EndSend
get_Zmodem
RZ_ReceiveData
RZ_32ReceiveData
RZ_InitReceiver
RZ_ReceiveBatch
RZ_ReceiveFile
RZ_GetHeader
RZ_SaveToDisk
RZ_AckBiBi
(Attempting to copy %s to %s... 
%s: Got 0.
Exit to MS-DOS key hit or carrier lost state or carrier gained
Request for sysop menu at main
Event key
Cron timeout
doRegular()
getCommand()
#NOSPASM in ROUTE.CIT
