Reading block
Carrier-Loss
Maximum errors exceeded
Timeout during STX
Timeout during SOH
CAN
Bad STX
Bad SOH
Timeout during blocknum
Timeout during ~blocknum
Blocknum mis-match
Duplicate record
Unexpected blocknum
Unexpected ~blocknum
Timeout data recv
Timeout crc hibyte
Timeout crc lobyte
Timeout checksum
Unexpected crc
Unexpected checksum
Awaiting startup NAK/"C"
No startup "C"
No startup NAK/"C"
Transmitting block
Timeout after block
CAN after block
Non-ACK after block
Timeout during EOT
CAN during EOT
Non-ACK during EOT
%-32s (Sector #%s) (Error #%s)
File transfer %s.
complete
cancelled