              
   %30s  3{0%s3}0
 %s @ %s
 %s
forwarding name
Exclusive %s now not forwarded
Exclusive %s now forwarded to %s
Exclusive %s now forwarded to %s @ %s
Your default %s is locked.
Verbose logout is forced on because Auto-verbose is turned on.
Default %s now "%s".
%s exclusion
<3L0>ist
<3A0>dd
<3R0>emove
<3B0>ack to previous menu
2Pick %s exclusion option:0 
 3Current %s exclusions:0
 3No %s excluded.0
exclusion string to add
Already excluded
exclusion string to remove
String not excluded
Back to previous menu
%s tags
2Pick %s tag option:0 
Current %s tags:
No %s tags defined
user to tag
tag for user
user to remove tags from
User not tagged.
<3T0> 3T0erminal type..... %s
3%02d0 %s
number of desired term type
0<3W0> Screen 3w0idth...... %-3d
<3U0> 3U0ppercase only.... %-3.3s
<3F0> Line3f0eeds......... %-3.3s
<3A0> T3a0bs.............. %-3.3s
<3N0> 3N0ulls............. %-3d
<3O0> IBM r3o0om prompts.. %-3.3s
<3M0> 3M0usic............. %-3.3s
<3L0> 3L0ines per screen.. %s
Screen pause off
<3R0> Att3r0ibutes........ 0Normal0, 1Blinking0, 2Inverted0, 3Boldface0, 4Underline0
2Pick terminal settings option to edit:0 
No terminal types defined.
Screen width
screen width
Pause on full screen
lines per screen (0 for continuous)
Duplicate or invalid address.
Nulls
number of nulls
Pointer edit menu
Uppercase only: %s
Linefeeds: %s
Tabs: %s
Attributes
Terminal type
[System Default]
IBM room prompts: %s
Music: %s
<3R0> 3R0eal name......... %s0
<3P0> 3P0hone number...... %s0
<310> Address line 310.... %s0
<320> Address line 320.... %s0
<330> Address line 330.... %s0
Real name
your real name
Phone number
your phone number [(xxx) xxx-xxxx]
Address line 1
line one of your address
Address line 2
line two of your address
Address line 3
line three of your address
<3P0> Prompt format..... %s0
<3T0> Time/date stamp... %s0
    Verbose   "....... %s0
<3N0> Net prefix........ %s0
Prompt format
prompt format
Net prefix
net prefix
Time/date stamp
time/date stamp
verbose time/date stamp
<3V0> 3V0erbose continue......... %s
<3S0> Confirm 3S0ave............. %s
<3A0> Confirm 3A0bort............ %s
<3E0> Confirm not .3E0O.......... %s
<3P0> S3p0ell checker mode....... %s
Verbose mode
Regular mode
Terse mode
Automatic mode
<3S0> Check apostrophe 3S0....... %s
<3C0> 3C0heck all-3c0aps........... %s
<3D0> Check 3d0igits............. %s
<3A0> 3A0dd word to dictionary
<3R0> 3R0emove word from dictionary
<3L0> 3L0ist words in dictionary
Confirm abort: %s
Check apostrophe S: %s
Check digits: %s
Confirm not .3E0>nter 3O0>ld after abort: %s
Check all-caps: %s
 3Words currently in personal dictionary:0
 3No words currently in personal dictionary.0
Spell checker mode: 
Valid options are 3A0utomatic, 3V0erbose, 3R0egular, or 3T0erse.
Confirm save: %s
Verbose continue: %s
word to add to personal dictionary
Word already in dictionary.
word to remove from personal dictionary
Word not in dictionary.
<3A0> 3A0uthor-based exclusions
<3N0> 3N0ode-based exclusions
<3T0> 3T0ext-based exclusions
<3R0> 3R0egion-based exclusions
<3E0> Exclude 3e0ncrypted...... %s
<3O0> N3o0tify on exclusion.... %s
<3M0> 3M0essage author tags
Author
Authors
Exclude encrypted messages: %s
Node
Nodes
Notify on exclusion: %s
Region
Regions
Text
<3D0> Room 3d0escriptions... %-3.3s
<3-0> Hall descriptions... %-3.3s
<3+0> Room info-lines..... %-3.3s
<310> Wide rooms.......... %-3.3s
<3X0> Auto ne3x0t hall...... %-3.3s
<3I0> Tw3i0rly cursor..... %-3.3s
<3V0> Auto 3v0erbose........ %-3.3s
<3L0> Verbose 3l0ogout...... %-3.3s
<3U0> List in 3u0serlog..... %-3.3s
<3H0> 3H0elpful hints....... %-3.3s
<3Y0> 3Y0ou are here........ %-3.3s
<3L0> 3L0ast old on new........ %-3.3s
<3M0> 3M0inibin stats....... %-3.3s
<3#0> 3#0 of users on login. %-3d
<3J0> Sub3j0ects............... %-3.3s
<3@0> Pause after msg........ %-3.3s
<3G0> Si3g0natures............. %-3.3s
<3C0> 3C0LS before msg......... %-3.3s
<3I0> T3i0tles/surnames..... %-3.3s
<3*0> View censored msg...... %-3.3s
<320> See borders & ads... %-3.3s
<3,0> Show 3comma0s in #s... %-3.3s
<3>0> Default hall........ %s
<3P0> Default 3p0rotocol.... %s
<3_0> Signature........... %s0
<3F0> 3F0orwarding to.......
<3&0> Address............. %s
<3T0> 3T0erminal settings%s
 (ANSI, width, lines per screen, etc...)
<350> Format strings%s
 (Prompt, time/date, net prefix)
<360> Personal information%s
 (Name, phone, address)
<3R0> %s 3r0ead options%s
 (Exclusions and tags)
<3Z0> Pointer edit menu%s
 (Message pointers, by room)
<3E0> %s 3e0ditor options%s
 (Verbose continue, spell checker)
Is this OK
Show commas in numbers: %s
Terminal options
Censored %s %%s
D%sisplay titles/surnames
o not d
D%sisplay subjects
D%sisplay signatures
Borders and Ads: %s
Auto verbose: %s
Number of users to show on login
number of users to show on login
Pause after %s: %%s
Format strings
Clear screen before %s: %%s
Minibin login stats: %s
Helpful hints: %s
You are here: %s
Last old on 3N0>ew: %s
Room descriptions: %s
%s descriptions: %%s
Room info-lines: %s
Auto next %s: %%s
Wide rooms: %s
Default %s
Forwarding address
Default protocol
2Protocol:0 
Personal information
Edit %s read options
%s editor options
Twirly cursor: %s
List in userlog: %s
Verbose logout: %s
  -- Your signature has been locked!
your signature
Privileges
<3N0> 3N0ame................ %s0
<3L0> 3L0ock T & Surname.... %-3.3s
<3K0> Loc3k0 user signature. %-3.3s
<3Y0> S3y0sop............... %-3.3s
<3D0> Ai3d0e................ %-3.3s
<3O0> N3o0de................ %-3.3s
<3P0> 3P0ermanent........... %-3.3s
<3E0> N3e0tuser............. %-3.3s
<3T0> 3T0witted............. %-3.3s
<3M0> 3M0ail................ %-3.3s
<3V0> 3V0erified............ %-3.3s
<340> Enter borders....... %-3.3s
<3H0> Lock default 3h0all... %-3.3s
<3C0> 3C0hat................ %-3.3s
<3R0> 3R0oom creation....... %-3.3s
<330> 33000 baud output..... %-3.3s
<310> Psycho user......... %-3.3s
<3U0> 3U0pload.............. %-3.3s
<350> Download............ %-3.3s
<3F0> Trap to print3f0ile... %-3.3s
<320> Calls per day....... %s
Unlimited
<3I0> T3i0me (minutes)...... 
N/A
    Password............ %s;%s
<3.0> Privileges
Chat: %s
Download: %s
Netuser: %s
Trap to printfile: %s
Lock default %s: %%s
Aide: %s
Minutes
Disable user's accounting
%s2 in account
Accounting turned off for system.
Lock user signature: %s
Lock title and surname: %s
Mail: %s
Name
new name
The name "%s" is reserved for use by Citadel.
Use this name anyway
Citadel is configured to refuse the name "%s".
Node: %s
Permanent: %s
Room creation: %s
Sysop: %s
Twit/Problem user: %s
Verified: %s
Upload: %s
Psycho: %s
Calls per day
number of calls allowed per day (0 for default)
300 baud simulation: %s
Change borders: %s
<3S0> 3S0et all pointers
<3N0> Set all pointers to 3n0ew
<3O0> Set all pointers to 3o0ld
<3R0> Set pointer for a 3r0oom
<3D0> 3D0isplay all pointers
<3B0> 3B0ack to previous menu
%s online, #%s to %s
2Pick pointer edit option:0 
Set pointer for particular room
New pointer for "%s"
Display all pointers.
%31s -> %s
All %s are new
All %s are old
Set all pointers
%s number
<3P0> S3p0ell-checker options
P unpauses: %s
<3N0> P u3n0pauses.......... %-3.3s
Aide
-- Sysops are always Aides.
Problem user
-- Aides are never Problem users.
<3>0> More prompt....... %s
More prompt
more prompt
 3Tagged %s:0
 3No tagged %s.0
 3Tags on %s %s:0
 3No tags on %s %s.0
2Pick %s editor option to edit:0 
2Pick %s read option to edit:0 
2Pick personal information option to edit:0 
2Pick format strings option to edit:0 
2Pick user privileges option to edit:0 
<3R0> Text 3r0eplacement options
2Pick spell-checker option:0 
Spell-checker options
Text replacement options
2Pick text replacement option:0 
Current text replacements:
Replace 3%s0 with 3%s0.
No text replacements defined
text to replace
replacement text
text to stop replacing
Text not replaced.
 3Replaced text:0
 3No replaced text.0
Text already replaced.
<3.0> User configuration
User configuration
Node attribute turned off.
Nodes must have an address.  Press 3Esc0 to abort.
new address
<330> Title............... %s
<340> Surname............. %s
Title
Surname
List
Address
<3*0> SuperSysop.......... %-3.3s
SuperSysop: %s
Sysop
-- SuperSysops are always Sysops.
<3U0> B3u0nny filter............. %s
Bunny filter: %s
<370> System Events%s
 (Notifications of Logins, Messages, etc.)
System Events
<3L0> 3L0og on/off................. %s
<3M0> 3M0essages in room........... %s
<3E0> 3E0xclusive messages......... %s
<3O0> User in/out of R3o0om........ %s
<3A0> Chat to 3A0ll................ %s
<3R0> Chat to 3R0oom............... %s
<3G0> Chat to 3G0roup.............. %s
<3U0> Chat to 3U0ser............... %s
2Pick system event notification to edit:0 
Log on/off: %s
Messages in room: %s
Exclusive messages: %s
User in/out of room: %s
Chat to all: %s
Chat to room: %s
Chat to group: %s
Chat to user: %s
<360> Banned.............. %-3.3s
Banned: %s
<3W0> Kill o3w0n messages... %-3.3s
Kill own messages: %s
<310> See own chats.............. %s
<320> Erase prompt before events. %s
<330> Seconds before AutoIdle.... %s
See own chats: %s
Erase prompt before events: %s
Seconds before AutoIdle
<3N0> 3N0ew message somewhere...... %s
New message somewhere: %s
