Error opening roomreq.tmp
 Fetching:
%s%s %-34s %s
 "%s" room not available to remote.%s
 No "%s" room on system.
 "%s" room not found for remote.%s
 Sending %s files.
 bad protocol
 Receiving mail file.
 Sending room request file.
 Waiting for transfer.
 Receiving %s files.
No such node in userlog!
NetCallout %s
NetLogout %s (Succeeded)
Networked with "%s"
  ----- %4d messages entered
  ----- %4d messages read
  ----- %4d messages expired
  ----- %4d messages duplicate
NetLogout %s (Failed)
 Incorporating:
                 Room:  New: Expired: Duplicate: 
อออออออออออออออออออออออออออออออออออออออออออออออออ
Error opening roomreq.out
 No "%s" Net ID on remote%s
 Net ID not found on other system.
 No "%s" room on remote%s
 Room not found on other system.
 %20.20s   Room not found on local system.
 No "%s" room local.%s
Totals:         
                (Rooms)(New)  (Exp)  (Dup)
Incorporating mail:
%s new %s, %s routed, %s rejected, and %s total.
%s netting with "%s"%s
#NODE
#ROOM
2Could not extract packet.0
Dialing ... 
timeout
2Could not copy mail file!0
aborted
NetDial (%s)
success
failure
2Could not copy packet!0
d
df
2Warning: Not enough memory to control room access on incorporation!0
{}
Invalid login verb/word (%s/%s)
Logging in ... 
failed
Fetching for
Incorporating from
2Waiting for transfer.0
2Sending/receiving files.0
2Hang up.0
2Generating %s0
Default
Must have default NODES.CIT entry!
2Uncompressing %s.0
{}
2Incorporating %s2 from %s.0
4                           Room   New  Expired  Duplicate 0
อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
Totals:                     
                           (Rooms)(New)  (Exp)  (Dup)
 %s new %s, %s routed, %s rejected, and %s total.
2Copying %s.0
%s69*.*
2Fetching %s2:0
2%s %s2 fetched.0
 %30.30s     (Skipped)
4 Roomname                       #   Roomname                       #0
3 new0
2Copying mail file.0
2Sending %s.0
2Compressing files.0
2Could not create packet.0
2Copying mail file back.0
2Copying packet %s.0
 Hang-up.
 Uncompressing %s files.
 Sending room request file.
 Receiving room request file.
#NETID
NETID.TMP
Error opening roomreq.in
 Room "%s" created.
 "%s" Room created.%s
 Room "%s" not created.
 "%s" Room not created.%s
 No "%s" Net ID on system.
 "%s" Net ID not found for remote.%s
 No "%s" room on system.
 Copying mail file.
 Compressing %s files.
 Sending mail and rooms.
 Receiving mail and rooms.
2Incorporating %s2 from %s.0
Fetch
nodename or alias
Incorporate
Room request
 Room "%s>" created.
 Room "%s>" not created.
 Net ID "%s" not found.
 File "%s" received.
 No access to room "%s>".
Build address
%s %s
(???) unk-nown
US %s
%ld %ld
 No access to Net ID "%s>".
{}
%s!..!%s
696969
{}
{}
%s\mailin.tmp
%s\roomreq.in
%s\roomreq.out
room.%hd
roomin.%hd
 %-20s  
msgin86.*
Try number %s.
 %30.30s   
3%3d0
%3d
    
อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
Totals:                     
{}
msgout86.%#03d
 %-30s
3 %-3d0
 ---
Citadel-86 Fetch
Citadel-86 Incorporate
%s %s:5%s
%s%s
%s69%s.*
%s\FILE69.%s
69
%s >> %s\%s
XXXTEMP
{}
FILE69.*
%s\ROOMREQ.%s
{}
{}
 %-3d
%s\FILE69.%s
%s69%s.%#03d
%s %s %s %s
%s %s %s
{}
ROOM.*
ROOMIN.*
MAILIN.TMP
MAILOUT.TMP
 %-20.20s  
 Room "%s" not found.%s
%s\ROOMREQ.TMP
ROOMREQ.TMP
 (%s)
{}
Citadel-86 networking slave mode not implemented.
{}
{}
   
MSGOUT86.*
 bad protocol
 Sending mail file.
 Receiving room request file.
{}
{}
This file is used internally by Citadel, and should not be edited or deleted
by humans under normal circumstances.
Editing this file may cause unexpected and undesirable effects.
