#USER
#MAYSUBSCRIBE
#MAYTELL
#MAYLIST
#INFOLINE
#INFOFILE
.tmp
%-20s "%s"%s
%-20s %d%s
#QUERY
Responding to %s
Mailing list
Response to %s
 Members of list:
 List has no members.
 Membership of list is private.
List is private.
Could not send mail.
#SUBSCRIBE
You are now subscribed to %s @ %s
You are not allowed to subscribe to %s @ %s
{}\
You are now unsubscribed from %s @ %s
You were not a member of %s @ %s
Responding to unknown command %s
Response to unknown command
The command "%s" is not recognized.
{}
To mailing list: %s @ %s
To: %s @ %s
To: %s
Mail to sender skipped.
%s is now unsubscribed from %s