ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ %s  %s  %s  %s  %s บ
F1 þ Shutdown 
F2 þ Startup  
F3 þ Request 
F4 þ Terminal 
F4 þ Status   
F5  þ Remote 
F5  þ Console
F6 þ Sysop fn 
F7 þ Bells off
F7 þ Bells on 
F7 þ Bells Cht
F8 þ ChatMode
F9 þ Chat on  
F9 þ Chat off 
F10 þ Help   
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
