Attributes
File set
Move file
Queue 
Rename file
Set file info
Unlink file
{}
Edit %6
%0 membership
%A changes
Insert %8
Kill %6
List %5 
Name %9
Window into %B
Insert %8 to old buffer

 Must be a sysop!
Jump to %s %s and %s %s
  -- %s not changed because you are in your personal %s.
You do not have %s access.
  -- System in floor mode, no effect.
Aide command: 
Read-only
Hidden
Attributes of file %s changed in %s] by %s
{}
<3N0> 3N0ame.............. %s
<3I0> 3I0nfoline.......... %s
<3D0> 3D0irectory......... %s
None
<3L0> App3l0ication....... %s
<3O0> Aut3o0 application.. %s
<3F0> Description 3F0ile.. %s
<3G0> Access 3G0roup...... %s
<3V0> Pri3v0ileges group.. %s
    Download-only..... %s
    Upload-only....... %s
    Read-only......... %s
    Group moderates... %s
<3H0> 3H0idden............ %s
<3B0> 3B0IO............... %s
<3Y0> Anon3y0mous......... %s
<3M0> 3M0oderated......... %s
<3E0> N3e0tworked/Shared.. %s
<3W0> Net3w0ork ID........ %s
<3P0> 3P0ermanent......... %s
<3U0> S3u0bject........... %s
<3R0> A3r0chive room...... %s
<3X0> Non-e3x0cludable.... %s
<3C0> Di3c0tionary........ %s
BIO %s: %%s
BIO %s
Must be a sysop to make %s>, %s> or %s) %s.
BIO
Dictionary
new dictionary file
Must be a SuperSysop or sysop at console to change %s.
Directory
Directory %s
No drive and path.
Now space %s.
Path
.\
%s does not exist.
Create
Could not create %s.
Download-only
Upload-only
Must be a sysop to make directories.
Networked/Shared %s: %%s
New Network ID
Net ID "%s" already exists.
Networked/Shared %s
Must be a sysop to make shared %s.
Description file
Display %s description file
Description filename
Must be a sysop to set %s descriptions.
Access %s
Currently: 
Must be a sysop to change %s for %s> or %s)
Cannot make %s> %s-only.
Hidden %s: %%s
Hidden %s
hidden
Info-line
new %s info-line
Application
Application filename
Moderated: %s
Moderated
Must be a sysop to make moderated %s.
Auto application %s: %%s
Auto application %s
  -- %s does not have an application.
Permanent: %s
Permanent
Directory %s are always permanent.
%s>, %s>, %s), and %s> are always permanent.
Archive
Archive filename
Ask for subject in %s: %%s
Privileges %s
%s moderates
Network ID
Must be a sysop to change Network IDs.
Nonexcludable: %s
Anonymous: %s
Anonymous
anonymous
Room "%s" changed to "%s" by %s
5%s%s%s
{}
destination %s
"%s" is not a directory %s.
Move file "%s" to %s "%s"
Copying file...
Cannot move "%s".
File %s moved to %s] from %s] by %s
{}
Enter %s2 in %s file was moved to
File moved to this %s:%s %s: %s byte%s%s %s
  -- Message nyms are locked.
name (Singular)
name (Plural)
what to do to %s2

msgNym()
source filename
destination filename
.
{}
file or files to unlink
  -- Must be a sysop to unlink multiple files.
In %s %s] by %s:
Unlink %s
YNAC
Continuous
%s%sFile %s %sunlinked.
could not be 
{}
%s file%s unlinked
.
Unwindow %s "%s>" from %s "%s"
Hall "%s" made invisible from room "%s>" by %s
%s "%s" made invisible from %s "%s>" by %s
{}
Window %s "%s>" to %s "%s"
Hall "%s" made visible from room "%s>" by %s
%s "%s" made visible from %s "%s>" by %s
Move %s
%s2 number to copy
%s not viewable.
{}
Not here.
Following message #%s inserted in %s> by %s:
Following %s #%s inserted in %s> by %s:
