2Sysop function:0 
Reset %s: %s
Cron command: 
Offhook
Date change
Enter config file: 
%s command: 
PATH.DAT
Info file reset
Journal room to file
Kill account
Login enabled
Mass delete
New user verification
Purge userlog
Run script
file to run
Show user
Userlog edit
View help text file
Exit Citadel
Zap empty rooms
Shell
Super shell
6.9 Network command: 
Auxmem debug info
 usexms: %d  xmshand: %u  xmssize: %uK
 emsframe: %u  emshand: %u  emssize: %uK
 vrthand: %u, vrtsize: %uK
 mtPage %3d is in 
heap
XMS 
EMS 
virt
 memory at %p. It holds slots %7lu to %7lu.
 rtPage %3d is in 
 frPage %3d is in 
 memory at %p.
Read by %s number
System status
Untwit %s
%s untwitted by %s
Full path download 
 -- Must be on console.
Currently: 
%s-specific membership 
 tbPage %3d is in 
New
User-specific membership
Force access
Twitted user %s terminated
System Monitors
Keyboard Monitor
Serial Port Monitor
Global room add/remove
Cron Monitor
Purge %s "%s"
Could not find message table entry!
Verify %s
%s verified by %s
Kill account
Un-verified user %s terminated
All *.CIT config files.
 -- Accounting disabled
full path of file to download
Only one filespec allowed
Protocol is not batch
All done
All events set to done.
Done event
Enter Cron file
Force event
List events
Next event set
Pause %s
Reset event
Zap event
event (0 = none)
No cron events.
 Current date is now: %s
 Current time is now: %s
Enter a new date & time
Cannot kill your own account, log out first.
Kill %s "%s"
"%s" terminated.
.
Delete all %s from %s
%s %s killed.
All messages from %s deleted
expression for %s access
Function was not implemented
VDISK device driver was detected
A20 error occurred
General driver error occurred
Unrecoverable driver error occurred
HMA does not exist
HMA is already in use
DX is less than /HMAMIN= parameter
HMA is not allocated
A20 line is still enabled
All extended memory is allocated
EMM handles are exhausted
Handle is invalid
Source handle is invalid
Source offset is invalid
Desination handle is invalid
Destination offset is invalid
Length is invalid
Overlap in move request is invalid
Parity error was detected
Block is not locked
Block is locked
Lock count overflowed
Lock failed
Smaller UMB is available
No UMBs are available
Internal error in EMM
Hardware malfunction
EMM is busy
Handle is invalid
Function is not defined
Handles are exhausted
Error exists in save or restore of mapping context
Allocation request specified more pages than are present
Allocation request specified more pages than are available
0 pages cannot be allocated
Request logical page is outside range of pages owned by handle
Illegal physical page number exists in mapping request
Page-mapping hardware-state save area is full
Mapping-context save failed; save area already contains context for handle
Mapping-context restore failed; save area does not contain context for handle
Subfunction parameter is not defined
Attribute type is not defined
Feature is not supported
Source and destination memory regions have same handle and overlap; data lost
Specified length for source or destination memory region longer than allocated
Conventional memory region and expanded memory region overlap
Specified offset is outside logical page
Region length exceeds 1MB
Source and destination memory regions have same handle and overlap; no exchange
Memory source and destination types are undefined
Error code is currently unused
Alternate map or DMA register sets are supported, but not specified one
Alternate map or DMA register sets are supported, but all are allocated
Alternate map or DMA register sets are not supported
Alternate map or DMA register sets are supported, not not defined or allocated
Dedicated DMA channels are not supported
Dedicated DMA channels are supported, but not specified one
Handle for specified name is not found
Handle with same name already exists
Memory address wraps
Invalid pointer is passed to function, or contents of source array corrupted
Access to function is denied by operating system
%s has:
 Sysop:
 Aide:
 Node:
 No accounting:
 Permanent:
 Net user:
 Problem user:
 No mail:
 Un-Verified:
 Range is %s - %s
%s2 number to read
Value out of range.
 XMS error: %s (%d)
The following empty %s deleted by %s: 
 ##   Type      String                Redo    Retry    Succeeded    Attempted
Zapped
      N/A    
      N/A
 2All events paused0
 3<0 - Current event
 3+0 - Can do event
 3-0 - Last attempt failed
<3N0> 3N0ame.................... %s
<3D0> 3D0escription............. %s
None
<3L0> 3L0ocked.................. %s
<3H0> 3H0idden.................. %s
<3U0> A3u0to-add................ %s
 sbPage %3d is in 
Kill
A "%s" %s already exists.
Description
new %s description
Locked
Lock %s from aides
Hidden
Make %s hidden
Auto-add
Make %s auto-add
The %s "%s" is always auto-add.
Group "%s" renamed to "%s"
Add all rooms to %s: %s
%s List
Cannot kill %s: or %s: %s, nose head!
 3%s %s still has the following %s:0
Hall "%s" created
<3N0> 3N0ame.................... %s
<3G0> Access 3g0roup............ %s
None
<3U0> 3U0sers can create rooms.. %s
<3D0> 3D0escription file........ %s
Group %s deleted
Hall "%s" deleted
%s still has %s.
Access %s
Cannot delete %s or %s %s.
Users can create rooms: %s
Operator-specific membership
Description file
Description
description filename
Hall %s renamed %s
Description file:
Users can create rooms:
The hall must have a name
Current hall: %s
Press a key...
 Unknown XMS error: %d
number of messages (0 for all)
Help Files
DOS Utilities
File List
Sysop Menu
Name: 
Description: 
Lock from aides: 
Hide group: 
Auto add group: 
desc
lock
hide
autoadd
Group must have a name
Cannot kill "%s" group.
Kill group "%s"
Cannot kill: group "%s" unknown.
Kill of group "%s" failed.
Creation of group "%s" failed.
Create group "%s"
Edit Group
Cannot edit: group "%s" unknown.
New Group
name of group to edit
name of group to kill
(No description)
Group: 
grp
A "%s" group does not exist.
Description file: 
Users may create rooms: 
file
roomok
(Add/Remove/[Both]):
Both
Lock group from aides
Hide group
Auto-add group
Group %s created
Add all users to group
Cron system is busy; try again later.
Hall must have a name
Create PATH.DAT
 EMS error: %s (%d)
Set success time
UMB segment number is invalid
 Unknown EMS error: %d
[On %s %s]
<3E0> D3e0fault hall............ %s
Table debugging 
Message
       Mail: %s
   Received: %s
      Reply: %s
    Problem: %s
    Madevis: %s
    Limited: %s
  Moderated: %s
Make Default hall: %s
       Copy: %s
        Net: %s
  Forwarded: %s
  Networked: %s
Mass E-Mail: %s
   Censored: %s
      Local: %s
      Inuse: %s
Room number: %s
   Location: %s
    To hash: %s
Author hash: %s
  Origin ID: %s
       Copy: %s
Room
room number to view
               Inuse: %s
           Permanent: %s
          Group-only: %s
  Boolean group-only: %s
Privilege group-only: %s
           Read-only: %s
           Moderated: %s
       Download-only: %s
         Upload-only: %s
              Shared: %s
           Directory: %s
              Hidden: %s
                 BIO: %s
             Subject: %s
           Anonymous: %s
             Archive: %s
         Application: %s
     Group moderates: %s
                Name: %s
              Net ID: %s
               Group: %s
    Privileged group: %s
Access forced to hall %s
%s by %s, in %s %s%s
PrevRoomMsg: %s
NextRoomMsg: %s
Cannot kill "%s" hall.
Kill hall "%s"
Cannot kill: hall "%s" unknown.
Kill of hall "%s" failed.
Creation of hall "%s" failed.
Create hall "%s"
Edit Hall
Cannot edit: hall "%s" unknown.
New Hall
name of hall to edit
name of hall to kill
Internal error.
Need hall list to move
(No group)
boolean group
Cannot kill "%s" room.
Kill room "%s"
Cannot kill: room "%s" unknown.
Kill of room "%s" failed.
name of room to kill
User "%s" logged in.
Kill user "%s"
Cannot kill: user "%s" unknown.
Kill of user "%s" failed.
name of user to kill
Editing user %s0.
  %b%D %H:%M
 %02d%s%s %-10s%-22.20s%-8s%-6s
3<0
3+0
3-0
Access forced to %s %s
Couldn't create UserAccountInfo!
Cannot make a hall non-default. You must make another hall default instead.
 -- Must be on console or a SuperSysop.
There are no remaining empty %s0 on the system.
