>
Continue
Find & Replace text
Print formatted
Replace text
Verify spelling
Word count
2Entry command:0 
  -- Buffer is full.
Delete %s buffer
Delete buffer
Encrypt %s
encryption key
  -- Message encryption not allowed in public messages.
  -- Message encryption not allowed.
%s-only
signature
Location
You are in the %s "%s" contained in the %s "%s".
Save
Checking spelling...
Confirm save
Subject
Allow ESC: %s
Link application
application to link
Change address
Special delivery options
Receipt confirmation requested
Message is not exclusive.
Name change
File input
text
 Text not found.
correct spelling
replacement text
Automatically replace "%s" with "%s" in future messages
Replace
 %s line%s, %s word%s, %s character%s
Bad %s!
3%s0 : 
(No suggestions)
%s unique word%s.
The word "%s" is not known. Correct the word
Add word to personal dictionary
<
3Possible correct spellings0 : 
 3Possible misspellings and corrections:0
 3Possible misspellings:0
No unknown words found.
Bad or missing %s!
  -- Your signature has been locked!
  -- Must be a sysop to send %s-only exclusive %s.
