Console unlocking has been disabled.
Command illegal: console locked.
Dropping DTR...
Output to speech synthesizer: %s.
Cannot turn on speech output: no sound driver with speech support loaded.
System request: %s.
System will be available in %ld:%02ld.
Cannot display status screen with windows visible.
Input from %s selected.
modem
console
Current user %s %s privileges.
now has
no longer has
Bells set to ring: %s.
always
only for the Chat command
never
Chat command: %s.
Current user's accounting: %s.
Debug mode is now: %s.
Could not turn debug mode on.
Scroll-back buffer not enabled in %s.
Cannot use scroll-back buffer while windows are visible.
Capture to file turned off.
Could not turn screen saver on.
Problem user
Ignore up time in %s: %s.
Verified
Exit Citadel
300 baud simulation
Console locked.
Cannot lock console: no #F6PASSWORD password in %s.
Local echo turned %s.
Quit.
disabled
Trapping output to file.
Could not open file to trap output to.
Incorrect password; console not unlocked.
Console unlocked.