%s (%d) Error: invalid data for %s
%s (%d) Error: %s not in function
%s (%d) Warning: unknown command %s
%s (%d) : Unknown type %d
%s (%d) : Variable %s not found
%s (%d) : Bad cmd
%s (%d) : No label %s
%s (%d) : No #ENDIF
%s (%d) : Cannot compare two CONSTs
STRUCT:
%s : Unknown type in argument %d of %s
%s (%d) : Too many parameters in call to %s
%s (%d) : Out of memory
%s (%d) : Unknown function (%s)
%s (%d) : #LOOP without #DO
%s (%d) : Unknown command type (%d)
This script needs to run under Citadel+/%ld compile %ld.
VOID
INT
UINT
LONG
ULONG
BOOL
STRING
FALSE
TRUE
%s (%d) : Don't know where to return to
Debugger
%s is:
.CSF
Line %d
Breakpoint reached.
Breakpoint cleared.
Breakpoint set.
Not enough memory to set breakpoint.
Watch window
Watch cleared.
Watch added.
Not enough memory to add watch.
Could not open watch window.
Single step
line for breakpoint
expression to evaluate
Script paused.
Script unpaused.
expression to watch
Abort the running script
Quit debugging
Source Code
Could not open file.
Line %d: %lu msec, %lu tot, %lu hits, %lu ave
%s (%d) : #WEND without #WHILE or #WHILENOT
%s (%d) : No #WEND
Error loading %s.
%30s : %s
%s (%d) Error: %s not allowed in #STRUCT definition
%s (%d) : Could not create parameter %s.
%s (%d) Error: #ENDSTRUCT without #STRUCT
%s (%d) : No #ENDSWITCH
