Configuration
Directory
Exclusive 
Forward 
Info file
Keyword search 
Local 
New 
Old 
Public 
Reverse 
Status
Textfile
Verbose 
With protocol download 
Archive file 
By date 
Header scan 
By %7 
%0-only 
%C
%4
%2log
From %8 # 
All 
Read 
.*
3Filename     Date         %sSize %s time0
Download
D/L
%-12s %s %11s %s%s
%-12s %s %9lu %s
%-12s 
%s byte%s in %s file%s.  %s bytes free.
Text download of file %s in room %s]
.
.
*.%s
Archive-view of file %s in room %s]
 3.RZ%c0>%s
 3.RZ?0> this menu
 3You are on:0 %s, %s, %s (%s.%s)
 3Running:0    %s%s%s%s
             %s
             Compiled on %s at %s
 3It is:0 %s%s
 3Up for:0 %s%s
 3Online:0 %s%s
, 3Logged in:0 %s
 3Logged in:0 %s
 3%s3log stats:0
 %s log entries, %s in use, %s calls
 %s node%s
, %s aide%s, %s sysop%s, %s problem %s, and %s permanent %s
 poop%s: %s0 (%s)
 3%s3 stats:0
 %s %s, %s in use
, %s auto-add, %s hidden, %s locked
{}
, %s %s-only, %s allowing %s creation
{}
 %s public, %s hidden, %s BIO, %s networked, %s directory, %s moderated, %s %s-only, and %s anonymous
 %s online, #%s to %s
 %s missing
,
 %s public, %s exclusive, %s networked, %s Local-only, %s moderated, %s censored, %s mass e-mail, 
and 
%s %s-only
, %s copied, and %s problem %s
%s.%d
 %s%cB %s space, %s %s slots
, %s base is %d%% full
 %s bytes average %s length
 %s entered, %s read%s
 by last caller
 3System stats / debugging:0
 OS/2 version %d.%02d running in DOS mode
 DOS version %d.%02d
 DESQview version %d.%02d
 Microsoft Windows version %d.%02d running in %s mode
standard
386 enhanced
 Windows version %d.%02d
 Using external %s driver: %s
video
serial
keyboard
sound
 Available file handles: %d
 %uK system memory,
 %s bytes free far heap memory
 %sKB total physical memory; %sKB available
 %sKB total paging file memory; %sKB available
 Command line: %s
 Heap is empty.
 Heap is corrupted.
 %s characters transmitted, %s characters received
 Connect rate %ld, Port rate %ld,%s using compression,%s using error correction
 not
 Port rate %ld
 Maximum inactive time: %s minute%s
date for listing
 %s version %d.%02d build %d.
Windows NT
Windows 95
[Unknown platform]
 %sKB total virtual memory; %sKB available
 Memory load is %d%%.
UPS
 Serial
 Connected to a remote computer by a%s connection.
 Not connected to a remote computer.
 Telnet
Unknown
 Transmitting at %s bps; receiving at %s bps
n Unknown
3Short name   Date         %sSize %s time%s0
  Full name
     MXhi48X%sXhi0X
Just one at a time 
