-B: Could not recognize speed "%s".
Unknown command line switch "%s".
Generating help files... 
%s.HLP
 (Could not open file!)
 (Could not load from executable!)
%s.BLB
, done.
Starts a new instance of Anticlimactic Teleservices' Citadel Bulletin Board
System known as Citadel+.

CTDL [-A] [-Bn] [-C] [-D] [-E] [-Fn] [-Mn] [-NB] [-NC] [-O] [-Ps | -Us | -!s]
  [-R[drive:][path]filename] [-V] [-X]
CTDL [-G[drive:][path]

  -A    Prompts for user to log in when Citadel starts and exits after user
        terminates intead of hanging up.
  -Bn   Sets baud rate; specify a valid rate from 300 to 115200.
  -C    Configures Citadel.
  -D    Uses direct screen writes until configuration information is loaded.
  -E    Enters CONFIG.CIT.
  -Fn   Specifies alternate minimum number of file handles required.  Use
        this only if you know what you are doing.
  -G[drive:][path]
        Generates help files, writing to current or optionally specified
        path.
  -Mn   Switches to specified video mode; use -M1000 for EGA/VGA 43/50 line
        mode.
  -NB   Turns off bells.
  -NC   Turns off chat.
  -O    Pops up utility menu.
  -Ps   Logs in user using specified initials and password, separated by a
        semicolon.
  -R[drive:][path]filename
        Runs specified script before giving room prompt.
  -Us   Logs in user using specified name.
  -V    Activates Debug mode.
  -X    Activates Batch mode.
  -!s   Networks with specified node.
  -#n   Uses specified serial port.

Currently, Batch mode's only functionality is automatic configuration when
ETC.TAB is not found.
Could not create console.
Press a key to exit...
