Ofs=%ld Retries=%d
CPS: %lu (%lu bytes)  Efficiency: %lu%%
No files specified
Zmodem error: %d, Can't %s %s
Keyboard Escape
Too many errors
CRC
Open
Open Character Device
Z-Send %s, %ld bytes, %d min.
%lu %lo %o
%s-Z%s %s
Sent
/32
Remote refused %s
Synchronizing to Offset %ld
Transfer cancelled
%lu %d min.
Trouble?
SKIP command received
Timeout
Memory overflow error
Resending from %s
Lost Carrier
Debris
Long pkt
ZFILE
ZSINIT
Ignoring "%s"
CMD
COMPL
Zmodem Init Problem %s
%s; %ld/%ld
bad position
Junk Block
Received
Zmodem Recv Problem %s
%ld %lo
Out of disk space
Already have %s
Dupe file renamed: %s
%s %s; %s%ld bytes, %d min.
Receiving
ASCII 
Write
 ???
0123456789abcdef
.001
