Hang-up after 
Save text file to disk
Unknown
Zmodem
1K Xmodem
"3H0" to hang up or any other key to abort countdown.
%d, 
%d.
  -- Your %s privileges have been removed
upload
download
  -- %s is %s-only.
Download 
 Total size: %s bytes
 Transfer time: %s
Not a batch protocol
Uploads temporarily disabled; only %sK free disk space.
Free disk space: %s bytes
Ready for file transfer
File size: %s byte%s
File size: %s block%s, %s byte%s
Transfer time: %s
 %s uploaded by %s%s Comments: %s
 %s uploaded by %s
Xmodem
Xmodem CRC
