Login 
  -- You are already logged in.
your initials
your password
.
.
.
.
%s%s Login of trapped %s: %s%s%s
JOKE
One moment please...
Your initials and password have expired.  Please enter new ones.
Resume interrupted %s2 from previous call
%s0 in old buffer. Use the 3.EO0 command to use it.
0Welcome back 
0Welcome 
!
The time is now: %s
You last called on: %s, %s ago.
You last called on: %s, which is in the future so some clock somewere is or was wrong.
You were the last caller.
You are caller #%s.
%s %s made
person has
people have
%s %s and left
call
calls
%s new %s since you were last here.
%s new %s0 on the system.
You have %s %s left today, 
%s %s more than your previous call.
%s %s fewer than your previous call.
no change from your previous call.
You have unlimited %s.
No record: Enter as new %s
No record: Request access
.
newUserFile()
Could not load terminal type "%s"!
Thank you, goodbye.
Is this OK
New user %s from %s
.
 Nym:        %s
 Baud:       %ld
your full real name
 Real name:  %s
your phone number [(xxx) xxx-xxxx]
 Phone:      %s
your address (1st of 3 lines)
your address (2nd of 3 lines)
your address (3rd of 3 lines)
 Address:    %s
the title you desire
 Title:      %s
%s - Titles not enabled.
s
the surname you desire
 Surname:    %s
%s - Surnames not enabled.
2Choose a default protocol:0 
your occupation
 Occupation: %s
where you heard about this BBS
 Where hear: %s
your birthdate
  -- Could not parse date. Use "3?0" for information.
 Birthdate:  %s %d, %d
What is your sex
MFU
Male
Female
Unspecified
 Sex:        
%s - Bad question code!
%hd
Login system busy; please try again later.
Warning: already logged in. Continue
4%s3 has logged in.
%sThe following line added for user %s%s
#BANPORT %s%s
Banning port %s due to attempted login of %s
Could not add port %s to %s for attempted login of %s
