3Filename           Size  Comments0
3Filename         Size0
3Comments0
%-*s%-18s
3Filename:0
%-*s%s%s
3Size:0
3Download time:0
 (download time %s)
%-*s%s %s  
3Date:0
3Uploaded by:0
3Comments:0
%-13s%10s  
25
Batch upload by %s0%s
%-12s %7lu %s
 %s: %s%s
Batch upload of %s to directory %s
File info changed for file %s by %s0
:
3Short name:0
3Full name:0
BXhi15X
BXhi12X
