Empty 
Application 
BIO 
Directory 
%0-only 
%C
%1 info
Keyword search 
Local 
Exclusive-%8 
New 
Old 
Permanent 
%D
Shared 
This %B only 
Verbose 
Window 
Excluded 
Anonymous 
Hidden 
Number of %9 
Known 
  -- This %s only does not work when using your personal %s.
%s belonging to %s "%s".
%s belonging to any %s.
wildcard expression to match
your personal %s
 3%s03 with unread %s03 along %s03:0
 3You have exclusive %s0 3in:0
 3You have unread old mail in:0
 3No %s03 in:0
 3No unseen %s03 in:0
 3Excluded %s:0
 3%s exiting to other %s:0
  %s : 
 3) => hidden %s0
 3} => bio %s0
 3%c => %s-only %s0
 3%c => directory %s0
