%s (%s) Warning: %s too long; must be fewer than %d characters.
Default
Must have a log entry for node "%s"
, or set a node's address to "%s.%s"
Must set address for log entry "%s"
mail.%s
{}
NODES.CIT
%s (%s) Warning: Invalid %s value "%s".
Not enough memory for group "%s"
%s (%s) Warning: unknown keyword %s
%s (%s) Warning: unknown %s keyword %s
ALL
Node:        %s
Region:      %s
Address:     %s.%s
PreDial:     %s
DialOut:     %s
Baud:        %ld
Login:       %s
Timeout:     %d
Protocol:    %c
Waitout:     %d
Mailtmp:     %s
Autohall:    %s
Autogroup:   %s
Mapunkgroup: %s
Not Active
Network:     %s%c
Zip:         %s
Unzip:       %s
Autoroom:    %d
Request:     %d
Gateway:     %d
Fetch:       %d
Netfail:     %d
Redial:      %d
Outputpace:  %d
0
1
2
