Use arrows to move window and ESC to quit.
Use arrows to resize window and ESC to quit.
Move...
Resize...
Enter 
Text Editor
: 
 Yes 
Yes
 No 
No
 Abort 
Abort
 Ok 
Ok
Enter data
Query
Error
Note
FYI...
Unknown system message: %d, %ld, %d, %p
