-B: Could not recognize speed "%s".
Unknown command line switch "%s".
Generating help files... 
%s.HLP
 (Could not open file!)
 (Could not load from executable!)
%s.BLB
, done.
Starts a new instance of Anticlimactic Teleservices' Citadel Bulletin Board
System known as Citadel+.

CTDL [-C] [-D] [-E] [-Fn] [-NB] [-NC] [-Ps | -Us | -!s] [-V] [-X]
  [-R[drive:][path]filename] 

  -C    Configures Citadel.
  -D    Uses direct screen writes until configuration information is loaded.
  -E    Enters CONFIG.CIT.
  -Fn   Specifies alternate minimum number of file handles required.  Use
        this only if you know what you are doing.
  -NB   Turns off bells.
  -NC   Turns off chat.
  -Ps   Logs in user using specified initials and password, separated by a
        semicolon, the first time you open a "New Local" connection.
  -Us   Logs in user using specified name the first time you open a "New
        Local" connection.
  -V    Activates Debug mode.
  -X    Activates Batch mode.
  -!s   Networks with specified node.
  -#n   Uses specified serial port.

Currently, Batch mode's only functionality is automatic configuration when
ETC.TAB is not found.
.
.
.
.
.
.
.
.
.
.
.
Could not create console.
Press a key to exit...
