// ENUMS.H -- Technically, forward declarations of enumerated types
//            is not ANSI-compliant.

enum UserCommandsE
	{
	UC_AIDEATTRIBUTES,	UC_AIDEEDITROOM,	UC_AIDEFILEINFOSET,
	UC_AIDEGROUP,		UC_AIDEHALL,		UC_AIDEINSERT,
	UC_AIDEJUMPTOAIDEANDMAINTENANCE,		UC_AIDEKILLROOM,
	UC_AIDELISTGROUP,	UC_AIDEMOVEFILE,	UC_AIDENAMEMESSAGES,
	UC_AIDEQUEUECLEAR,	UC_AIDEQUEUEINSERT,	UC_AIDEQUEUEAUTOMARK,
	UC_AIDEQUEUEKILL,	UC_AIDEQUEUELIST,	UC_AIDEQUEUEMOVE,
	UC_AIDEQUEUESORT,	UC_AIDERENAMEFILE,	UC_AIDEQUEUEROOMMARK,
	UC_AIDESETFILEINFO,	UC_AIDEUNLINK,		UC_AIDEWINDOW,
	UC_AIDEMOVEROOM,	UC_AIDECOPYMESSAGE,	UC_ENTERAPPLICATION,
	UC_ENTERBORDER,		UC_ENTERDOOR,		UC_ENTERCONFIGURATION,
	UC_ENTERHALL,		UC_ENTERNAME,		UC_ENTERPASSWORD,
	UC_ENTERROOM,		UC_ENTERTEXTFILE,	UC_ENTERTITLESURNAME,
	UC_EXCLUDEROOM,		UC_INVITEUSERLIST,	UC_ENTERWITHPROTOCOL,
	UC_INVITEROOMLIST,	UC_INVITEUSER,		UC_INTRO,
	UC_TERMINATESTAY,	UC_EXPERTTOGGLE,	UC_TERMINATEQUITALSO,
	UC_VERBOSETOGGLE,	UC_Y,				UC_FINGERDELETE,
	UC_FINGEREDIT,		UC_FINGERLIST,		UC_FINGERUSER,
	UC_READDIRECTORY,	UC_READHALLS,		UC_READCONFIGURATION,
	UC_READINFOFILE,	UC_READSTATUS,		UC_READTEXTFILE,
	UC_READUSERLOG,		UC_READARCHIVE,		UC_READWITHPROTOCOL,
	UC_CHATALL,			UC_CHATUSER,		UC_CHATGROUP,
	UC_CHATROOM,		UC_CHATCONSOLE,

	UC_NUM,
	};

enum MenuNames
	{
	M_ENTOPT,			M_KNOWN,			M_READOPT,
	M_GRPGLOB,			M_EDIT,				M_TERMINATE,
	M_SYSNET,			M_SYSGROUP, 		M_SYSHALL,
	M_SYSENTER, 		M_AIDE,				M_AIDEQUEUE,
	M_MAINDOT,			M_DOORS,			M_CRON,
	M_SYSOP,			M_MAINOPT,			M_VOLKSWAGEN,
	M_BULLETINS,		M_INVITE,			M_FILEQUEUE,
	M_HELP,				M_PERSONAL, 		M_PERSONALADD,
	M_FINGER,			M_EDITTEXT,			M_SYSTABLE,
	M_READWC,			M_ENTERWC,			M_UPLOAD,
	M_DOWNLOAD,			M_RESPONSEDOWNLOAD,	M_WHO,
	M_CHAT,

	MAXMENUS,
	};

enum HelpFiles
	{
    H_ACCOUNT,          H_AIDE,             H_ANSI,
	H_CONFIG,			H_DOHELP,			H_DOORS,
	H_FILES,			H_GROUPS,			H_HALLS,
	H_HELP,				H_INTRO,			H_LOGIN,
	H_MESSAGES,			H_NETWORK,			H_QUEUE,
	H_ROOMS,			H_ROOMSYS,			H_SPECIAL,
    H_SPELL,            H_SYSOP,            H_CHAT,

	MAXHLP,
	};

enum BlurbFiles
	{
	B_BULLETIN, 		B_CHAT, 			B_CLOSESYS,
	B_ENTRY,			B_GOODBYE,			B_HELLO,
	B_LOGOUT,			B_NEWMSG,			B_NEWQUEST,
	B_NEWROOM,			B_NOCHAT,			B_NOLOGIN,
	B_PASSWORD, 		B_TEXTUP,			B_TOOLOW,
	B_USERINFO, 		B_VERIFIED, 		B_FILENSRT,
	B_WCDOWN,			B_WCUP, 			B_NOROUTE,
	B_CHATTED,			B_CENSOR,			B_RESUME,
	B_DISCLAIM, 		B_AD,				B_NOANSWER,
	B_TOOMANY,			B_MOREPRMP, 		B_REALNAME,
	B_PHONENUM, 		B_ADDRESS,			B_NETPREFX,
	B_TIME, 			B_PROMPT,			B_MSGNYM,
	B_COLORS,			B_ENTERNYM, 		B_ENCRYPT,
	B_WOWCOUNT, 		B_CALLIMIT, 		B_WIDTH,
	B_LENGTH,			B_NULLS,			B_NUMUSERS,
	B_UNLINK,			B_DATESET,			B_TIMESET,
	B_SIGNATUR, 		B_SUBJECT,			B_LINKAPP,
	B_MNAMECHG, 		B_DIALOUT,			B_TITLESUR,
	B_NEWQMSG,			B_KNOWNGRP, 		B_YN,
	B_YNA,				B_YNAC, 			B_BA,
	B_YNK,				B_MFU,				B_KNWNKYWD,
	B_PWRFAIL,			B_NEWQFNGR,			B_AIDEQUEUEAUTO,
	B_BANPORT,			B_BANNED,

	MAXBLBS
	};

enum SexE
	{
	SEX_UNKNOWN,	SEX_MALE,		SEX_FEMALE,
	};

enum CITEVENTS
	{
	EVT_LOGIN,			EVT_LOGOUT, 		EVT_ROOMPROMPT,
	EVT_DOWNLOAD,		EVT_READDIR,		EVT_READINFO,
	EVT_UPLOAD, 		EVT_CHAT,			EVT_SAVEMSG,
	EVT_READMSG,		EVT_READMSGS,		EVT_BEEP,
	EVT_CARRIER,		EVT_NEWROOM,		EVT_ANONYMOUS,
	EVT_PASSWORD,		EVT_AIDE,			EVT_SYSOP,
	EVT_ERROR,			EVT_NETWORK,		EVT_ACCOUNT,
	EVT_APPLIC, 		EVT_CRON,			EVT_HACK,
	EVT_NEWUSER,		EVT_SMALLCHAT,		EVT_STARTUP,
	EVT_SHUTDOWN,		EVT_WRITENETMAIL,	EVT_READNETMAIL,
	EVT_STOREMESSAGE,	EVT_LOADMESSAGE,	EVT_STORENETMESSAGE,
	EVT_LOADNETMESSAGE,

	EVT_NUMEVTS,
	};

enum CronKeywordsE
	{
	CR_DO,				CR_HOURS,			CR_DAYS,
	CR_REDO,			CR_RETRY,			CR_PRIORITY,
	CR_MONTHS,			CR_DATES,

	CR_NUMCRON
	};

enum CronTypesE
	{
	CR_NET,				CR_SHELL_1,			CR_SHELL_2,
	CR_SHUTDOWN,		CR_CHAT_ON,			CR_CHAT_OFF,
	CR_NET69_IN,		CR_NET69_OUT,		CR_COMMAND,
	CR_NET86_IN,		CR_NET86_OUT,

	CR_NUMTYPES
	};

enum InternalProtocols
	{
	IP_XMODEM,	IP_CRCXMODEM,	IP_ONEKXMODEM,	IP_ZMODEM, IP_ERROR,
	};

enum TermTypeE
	{
	TT_UNKNOWN, 	TT_DUMB,	TT_ANSI,

	TT_NUM,
	};

enum MenuE
	{
	MENU_READ,		MENU_ENTER,			MENU_AIDE,		MENU_AIDEQUEUE,
	MENU_INV,		MENU_TERM,			MENU_FINGER,	MENU_KNOWN,
	MENU_PERSONAL,	MENU_PERSONALADD,	MENU_FILEQUEUE,	MENU_EDIT,
	MENU_WHO,		MENU_CHAT,

	MENU_NUM
	};

enum MaySeeMsgType
    {
    MSM_ERROR,          MSM_COPYSCROLLED,   MSM_CENSORED,       MSM_GOOD,
    MSM_NOTLOGGEDIN,    MSM_COPYOWNTWIT,    MSM_RELEASEDORIG,   MSM_TWIT,
    MSM_MODERATED,      MSM_NOTINGROUP,     MSM_GROUPBAD,       MSM_MAIL,
	MSM_SCROLLED,
    };

enum KillFileE
	{
	KF_USER,	KF_NODE,	KF_TEXT,	KF_REGION,

	KF_NUM
	};


enum discardableType
	{
	DD_STRING,		DD_RAWDATA, 	DD_STRCMP,		DD_STRCMPK,
	DD_STRCMPT, 	DD_STRCMPA, 	DD_STRCMPX, 	DD_FORMATTED,
	DD_FORMATTEDX,	DD_RAWDATAX,

	DD_LAST
	};

enum TrapKeywords
	{
	T_ALL,				T_CARRIER,			T_LOGIN,
	T_NEWROOM,			T_ANONYMOUS,		T_CHAT,
	T_PASSWORD, 		T_AIDE, 			T_SYSOP,
	T_UPLOAD,			T_DOWNLOAD, 		T_ERROR,
	T_NETWORK,			T_ACCOUNT,			T_APPLIC,
	T_CRON, 			T_HACK,				T_DEBUG,
    T_PORT,

	T_NUMTRAP
	};

enum NewUserQuestions
	{
	NUQ_REALNAME,		NUQ_PHONENUMBER,	NUQ_ADDRESS,
	NUQ_OCCUPATION, 	NUQ_BIRTHDAY,		NUQ_SEX,
	NUQ_WHEREHEAR,		NUQ_COLORS, 		NUQ_TITLE,
	NUQ_SURNAME,		NUQ_PROTOCOL,		NUQ_MESSAGE,
	NUQ_FINGER,

	NUQ_NUMQUEST
	};
