%y%b%D  %H:%M:%S
Up for: %s
%s: %-30s
%-39s
Room: %-30s
{Invalid}
Time: %s
Room: %-55s
Special time
%s: %10ld
%s: %-70s
Personal
%11s: %-10lu%10s: %-12d %s: %-13ld
Received
Entered
Poop
%11s: %-10lu%10s: %-30d
%11s: %-10lu%10s: %-12d
Transmitted
Read
Free: %s bytes
%s %sK
XMS used:
EMS used:
Virt used:
Connect rate %ld, Port rate %ld
, error correction
, compression
Port rate %-60ld
%-65s%s
System event
Time
%b%D  %H:%M
{}
{}
{}
{}
{}
{}
Don't Know
Main Menu
Sysop
Prompt
Entering Message
Dial Out
Networking
Enter Border
Read Messages
Reading Help
Read Userlog
Read Status
Read Configuration
Intro
Download
Upload
Chat
Enter
Volkswagen
Exclude
Goto
Known
Logout
Read
Small Chat
Aide
Enter Configuration
Enter Door
Enter Hall
Enter Password
Enter Room
Enter Textfile
Enter WC-Protocol
Enter Application
Enter Name
Enter Surname
Enter Menu
Bypass
Known Rooms
Known Halls
Known Room Info
Known Menu
Terminate Menu
Terminate Quit-Also
Terminate Stay
Read Directory
Read Infofile
Read Halls
Read Textfile
Read WC-Protocol
Read Zip File
Read Menu
Aide Attributes
Aide Chat
Aide Edit Room
Aide File Set
Aide Group
Aide Hall
Aide Insert
Aide Kill
Aide List Groups
Aide Move File
Aide Message Name
Aide Queue
Aide Queue Mark
Aide Queue Clear
Aide Queue Insert
Aide Queue Kill
Aide Queue List
Aide Queue Room-Mark
Aide Queue Sort
Aide Rename File
Aide Set Fileinfo
Aide Unlink
{}
Aide Window
Aide Move Room
Aide Copy Message
Aide Menu
Sysop Reset Maintenance
Sysop Cron
Sysop Off-Hook
Sysop Date Set
Sysop Enter Cfg
Sysop Group
Sysop Hall
Sysop Info Reset
Sysop Room Journal
Sysop Kill User
Sysop Mass-Delete
Sysop NewUser Verify
Sysop Run Script
Sysop Show User
Sysop Edit User
{}
Sysop Exit to DOS
Sysop Kill Empty Rooms
Sysop Shell
Sysop Net 6.9 Menu
Sysop Auxmem Debug
Sysop Read By Message #
Sysop Reconfigure
Sysop Menu
Net 6.9 Fetch
Net 6.9 Incorporate
Net 6.9 Generate Room Request File
Net 6.9 Menu
Sysop Full-Path download
* Security Violation *
Login
scrollback
consysop
File Queue List
File Queue Remove
File Queue Clear
File Queue Add
Mail Scan
Personal hall
Personal hall menu
Personal hall add
Personal hall remove
Personal hall list
Personal hall use
Personal hall add all
Personal hall add local
Personal hall add room
Personal hall add menu
Personal hall clear
Citadel-86 Fetch
Citadel-86 Incorporate
Finger
Finger User
Finger Edit
Finger Menu
Sysop Table debugging
Finger List
Who
Who Menu
Chat Menu
